// <auto-generated />
using System;
using HealthRater.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthRater.Data.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerHealthRaterDbContext))]
    partial class SqlServerHealthRaterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthRater.Data.Entities.AssessmentParameterScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("NormalizedValue")
                        .HasColumnType("float");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("RawValue")
                        .HasColumnType("float");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("AssessmentId", "ParameterKey")
                        .IsUnique();

                    b.ToTable("AssessmentParameterScores", t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentParameterScores_Score", "Score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("HealthRater.Data.Entities.HealthAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeAtAssessment")
                        .HasColumnType("int");

                    b.Property<int>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirthAtAssessment")
                        .HasColumnType("date");

                    b.Property<int>("HeartRateRecovery")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("HeightUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Hip")
                        .HasColumnType("float");

                    b.Property<string>("HipUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<int>("RestingHeartRate")
                        .HasColumnType("int");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SexAtAssessment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalHealthRating")
                        .HasColumnType("int");

                    b.Property<int>("TotalPossibleScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Waist")
                        .HasColumnType("float");

                    b.Property<double>("WaistToHeightRatio")
                        .HasColumnType("float");

                    b.Property<double>("WaistToHipRatio")
                        .HasColumnType("float");

                    b.Property<string>("WaistUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status", "CompletedAt");

                    b.ToTable("HealthAssessments", t =>
                        {
                            t.HasCheckConstraint("CK_HealthAssessments_Age", "AgeAtAssessment BETWEEN 18 AND 100");

                            t.HasCheckConstraint("CK_HealthAssessments_Total", "TotalHealthRating >= 0 AND TotalHealthRating <= TotalPossibleScore");
                        });
                });

            modelBuilder.Entity("HealthRater.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AvatarUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.UserAvatar", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserAvatars");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.AssessmentParameterScore", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.HealthAssessment", "Assessment")
                        .WithMany("ParameterScores")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.HealthAssessment", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.User", "User")
                        .WithMany("HealthAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "EnergyStrengthStamina", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("int")
                                .HasColumnName("EnergyStrengthStaminaMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("float")
                                .HasColumnName("EnergyStrengthStaminaScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("int")
                                .HasColumnName("EnergyStrengthStaminaRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "Immunity", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("int")
                                .HasColumnName("ImmunityMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("float")
                                .HasColumnName("ImmunityScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("int")
                                .HasColumnName("ImmunityRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "Longevity", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("int")
                                .HasColumnName("LongevityMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("float")
                                .HasColumnName("LongevityScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("int")
                                .HasColumnName("LongevityRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "MentalEmotional", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("int")
                                .HasColumnName("MentalEmotionalMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("float")
                                .HasColumnName("MentalEmotionalScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("int")
                                .HasColumnName("MentalEmotionalRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.Navigation("EnergyStrengthStamina")
                        .IsRequired();

                    b.Navigation("Immunity")
                        .IsRequired();

                    b.Navigation("Longevity")
                        .IsRequired();

                    b.Navigation("MentalEmotional")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.UserAvatar", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.User", "User")
                        .WithOne("Avatar")
                        .HasForeignKey("HealthRater.Data.Entities.UserAvatar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.HealthAssessment", b =>
                {
                    b.Navigation("ParameterScores");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.User", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("HealthAssessments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
