// <auto-generated />
using System;
using HealthRater.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthRater.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteHealthRaterDbContext))]
    partial class SqliteHealthRaterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("HealthRater.Data.Entities.AssessmentParameterScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NormalizedValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RawValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("AssessmentId", "ParameterKey")
                        .IsUnique();

                    b.ToTable("AssessmentParameterScores", t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentParameterScores_Score", "Score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("HealthRater.Data.Entities.HealthAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgeAtAssessment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BloodPressureDiastolic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BloodPressureSystolic")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bmi")
                        .HasColumnType("REAL");

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartRateRecovery")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("HeightUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Hip")
                        .HasColumnType("REAL");

                    b.Property<string>("HipUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<int>("RestingHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalHealthRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPossibleScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Waist")
                        .HasColumnType("REAL");

                    b.Property<double>("WaistToHeightRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("WaistToHipRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("WaistUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status", "CompletedAt");

                    b.ToTable("HealthAssessments", t =>
                        {
                            t.HasCheckConstraint("CK_HealthAssessments_Age", "AgeAtAssessment BETWEEN 18 AND 100");

                            t.HasCheckConstraint("CK_HealthAssessments_Total", "TotalHealthRating >= 0 AND TotalHealthRating <= TotalPossibleScore");
                        });
                });

            modelBuilder.Entity("HealthRater.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.AssessmentParameterScore", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.HealthAssessment", "Assessment")
                        .WithMany("ParameterScores")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.HealthAssessment", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.User", "User")
                        .WithMany("HealthAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "EnergyStrengthStamina", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EnergyStrengthStaminaMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("REAL")
                                .HasColumnName("EnergyStrengthStaminaScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EnergyStrengthStaminaRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "Immunity", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ImmunityMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("REAL")
                                .HasColumnName("ImmunityScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ImmunityRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "Longevity", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LongevityMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("REAL")
                                .HasColumnName("LongevityScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LongevityRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.OwnsOne("HealthRater.Data.Entities.StateScoreSnapshot", "MentalEmotional", b1 =>
                        {
                            b1.Property<Guid>("HealthAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxRawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MentalEmotionalMax");

                            b1.Property<double>("NormalizedScore")
                                .HasColumnType("REAL")
                                .HasColumnName("MentalEmotionalScore");

                            b1.Property<int>("RawScore")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MentalEmotionalRaw");

                            b1.HasKey("HealthAssessmentId");

                            b1.ToTable("HealthAssessments");

                            b1.WithOwner()
                                .HasForeignKey("HealthAssessmentId");
                        });

                    b.Navigation("EnergyStrengthStamina")
                        .IsRequired();

                    b.Navigation("Immunity")
                        .IsRequired();

                    b.Navigation("Longevity")
                        .IsRequired();

                    b.Navigation("MentalEmotional")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("HealthRater.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.HealthAssessment", b =>
                {
                    b.Navigation("ParameterScores");
                });

            modelBuilder.Entity("HealthRater.Data.Entities.User", b =>
                {
                    b.Navigation("HealthAssessments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
